[2021-03-16 00:46:48,708] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: marketvol.query_data 2021-03-16T00:46:14.245328+00:00 [queued]>
[2021-03-16 00:46:48,767] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: marketvol.query_data 2021-03-16T00:46:14.245328+00:00 [queued]>
[2021-03-16 00:46:48,767] {{taskinstance.py:880}} INFO - 
--------------------------------------------------------------------------------
[2021-03-16 00:46:48,768] {{taskinstance.py:881}} INFO - Starting attempt 1 of 3
[2021-03-16 00:46:48,768] {{taskinstance.py:882}} INFO - 
--------------------------------------------------------------------------------
[2021-03-16 00:46:48,792] {{taskinstance.py:901}} INFO - Executing <Task(PythonOperator): query_data> on 2021-03-16T00:46:14.245328+00:00
[2021-03-16 00:46:48,799] {{standard_task_runner.py:54}} INFO - Started process 8694 to run task
[2021-03-16 00:46:48,874] {{standard_task_runner.py:77}} INFO - Running: ['airflow', 'run', 'marketvol', 'query_data', '2021-03-16T00:46:14.245328+00:00', '--job_id', '22', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/stock-market-dag.py', '--cfg_path', '/tmp/tmp1z4api1i']
[2021-03-16 00:46:48,875] {{standard_task_runner.py:78}} INFO - Job 22: Subtask query_data
[2021-03-16 00:46:48,951] {{logging_mixin.py:112}} INFO - Running <TaskInstance: marketvol.query_data 2021-03-16T00:46:14.245328+00:00 [running]> on host 6ef8928b229b
[2021-03-16 00:46:49,015] {{taskinstance.py:1150}} ERROR - No columns to parse from file
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/stock-market-dag.py", line 66, in query
    apple_df = pd.read_csv('/usr/local/spark/resources/data/query/aapl-data.csv')
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2021-03-16 00:46:49,033] {{taskinstance.py:1194}} INFO - Marking task as UP_FOR_RETRY. dag_id=marketvol, task_id=query_data, execution_date=20210316T004614, start_date=20210316T004648, end_date=20210316T004649
[2021-03-16 00:46:53,683] {{local_task_job.py:102}} INFO - Task exited with return code 1
